name: "Shared: release-bump-version"
on:
    workflow_call:
        inputs:
            version_bump:
                description: 'Version bump type'
                required: true
                type: string
            custom_version:
                description: 'Custom version (only used if "custom" is selected, e.g., 1.0.0 or 1.0.0-preview.1)'
                required: false
                type: string
                default: ''
        outputs:
            new_version:
                description: 'Calculated semantic version'
                value: ${{ jobs.bump-version.outputs.new_version }}
            tag_name:
                description: 'Created git tag name'
                value: ${{ jobs.bump-version.outputs.tag_name }}

jobs:
    bump-version:
        name: "CI: bump-version"
        runs-on: ubuntu-latest
        permissions:
            contents: write
        outputs:
            new_version: ${{ steps.version-bumper.outputs.version }}
            tag_name: ${{ steps.version-bumper.outputs.tag }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v7
                with:
                    fetch-depth: 0
                    token: ${{ secrets.RELEASE_TOKEN }}

            -   name: Bump Version
                id: version-bumper
                uses: ./
                with:
                    version_file: VERSION
                    bump: ${{ inputs.version_bump }}
                    custom_version: ${{ inputs.custom_version }}
                    commit: 'true'
                    tag: 'true'
                    push: 'true'
                    floating_major_version: 'true'
